import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav className="bg-white border-b border-gray-200 p-4 flex gap-6 shadow-sm">
                    <div className="font-bold text-xl text-black">Mi App 🚀</div>
                    <div className="flex gap-4">
                        <Link href="/" className="text-gray-600 hover:text-blue-600 font-medium">
                            Home
                        </Link>
                        <Link href="/perfil" className="text-gray-600 hover:text-blue-600 font-medium">
                            Perfil
                        </Link>
                    </div>
                </nav>

                <main className="container mx-auto px-4 py-6">
                    {children}
                </main>
            </body>
        </html>
    );
}
